{% set version = "16.0.0" %}

package:
  name: path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/path/path-{{ version }}.tar.gz
  sha256: 48ddde18c6a15d40233bffeca882b6297a3e3a058903f1d4b52671cb8efd4018

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools >=42
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.6
    - importlib_metadata >=0.5  # [py<38]

test:
  imports:
    - path
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jaraco/path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module wrapper for os.path
  description: |
    path implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://path.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jaraco/path/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path

extra:
  recipe-maintainers:
    - nehaljwani
