{% set name = "path" %}
{% set version = "17.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dfcbfec8b4d960f3469c52acf133113c2a8bf12ac7b98d629fa91af87248d42

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools_scm >=3.4.1
  run:
    - python

{% set tests_to_deselect = "" %}
# raise NotImplementedError("Ownership not available on this platform.")
{% set tests_to_deselect = tests_to_deselect + " --deselect=tests/test_path.py::TestOwnership::test_get_owner" %}  # [win]
# test_no_dependencies: subprocess.CalledProcessError: Command '['$PREFIX/bin/python', '-S', '-c', 'import path']' returned non-zero exit status 1.
{% set tests_to_deselect = tests_to_deselect + " --deselect=tests/test_path.py::test_no_dependencies" %}
test:
  source_files:
    - tests
  imports:
    - path
  requires:
    - pip
    - pytest >=6,!=8.1
    - more-itertools
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests {{ tests_to_deselect }}

about:
  home: https://github.com/jaraco/path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module wrapper for os.path
  description: |
    path implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://path.readthedocs.io/en/latest
  doc_source_url: https://github.com/jaraco/path/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path

extra:
  recipe-maintainers:
    - nehaljwani