{% set version = "13.2.0" %}

package:
  name: path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/path/path-{{ version }}.tar.gz
  sha256: 10a149813a921540fd48ad639ec9157d08c2149ac2bcc399c74304450f70fdf2

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python
    - importlib_metadata >=0.5  # [py<38]

test:
  imports:
    - path

about:
  home: https://github.com/jaraco/path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module wrapper for os.path
  description: |
    path implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://path.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jaraco/path/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
